# Build Lifecycle
# before_install -> install -> before_script -> script
# -> after_success or after_failure -> after_script

language: android
sudo: false
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_API_LEVEL=25
      ANDROID_BUILD_TOOLS_VERSION=25.0.2
      ANDROID_TARGET_API_LEVEL=25
      ANDROID_TARGET="android-"
      ANDROID_ABI=default/armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - android-$ANDROID_TARGET_API_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_TARGET_API_LEVEL

before_script:
  # Make gradlew have permission to execute
  - chmod +x gradlew
  # Create, start and wait device
  - echo no | android create avd --force -n test -t "$ANDROID_TARGET$ANDROID_TARGET_API_LEVEL" --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  # Default is "./gradlew build connectedCheck"
  #- ./gradlew --full-stacktrace build -PdisablePreDex
